// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "dio-desafio-playgroud=xcode",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "dio-desafio-playgroud=xcode",
            targets: ["AppModule"],
            bundleIdentifier: "Rodrigo-Chiozi.dio-desafio-playgroud-xcode",
            teamIdentifier: "CE3BMT4BF4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .weights),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
